easy_admin:
    design:
      assets:
        css:
          - 'bundles/app/css/style.css'
      form_theme:
        - '@EasyAdmin/form/bootstrap_4.html.twig'
        - '@A2lixTranslationForm/bootstrap_4_layout.html.twig'
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
        - 'admin/form.html.twig'
    entities:
        CmsPage:
          label: 'Page'
          class: App\Entity\CmsPage
          form:
            fields:
              - { type: 'group', label: 'Page' }
              - { property: 'translations', type: 'A2lix\TranslationFormBundle\Form\Type\TranslationsType' }
              - { type: 'group', columns: '6', label: 'Block text'}
              - { property: 'textBlocs', type: 'collection', type_options: { allow_delete: true, allow_add: true, by_reference: false, entry_type: 'App\Form\TextBlocType' } }
              - { type: 'group', columns: '6', label: 'Block image'}
              - { property: 'textImageBlocs', type: 'collection', type_options: { allow_delete: true, allow_add: true, by_reference: false, entry_type: 'App\Form\TextImageBlocType' } }

