vich_uploader:
    db_driver: orm

    mappings:
        block:
            uri_prefix: '%app.path.blocks_images%'
            upload_destination: '%kernel.project_dir%/public/%app.path.blocks_images%'
